### ISSUE TITLE
RAM is out of memory during Training (Not GPU VRAM)

### ISSUE THREAD

**Issue by atlonxp** [SWivid/F5-TTS#440]
### Checks

- [X] This template is only for question, not feature requests or bug reports.
- [X] I have thoroughly reviewed the project documentation and read the related paper(s).
- [X] I have searched for existing issues, including closed ones, no similar questions.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Question details

**Title**: GPU Node VRAM Out of Memory (OOM) During Training

**Description**:  
I'm encountering an **Out of Memory (OOM)** issue on my GPU node during training, which has 4 x A100 GPUs with a combined VRAM of **500 GB**. The model I'm training is configured with a large batch size and gradient accumulation, but despite using mixed precision and optimizing memory usage, VRAM keeps running out.

**Steps to Reproduce**:
1. Train the model with the following configuration:
   - **Batch size per GPU**: 16,000
   - **Gradient Accumulation Steps**: 32
   - **Mixed Precision**: BF16
2. Dataset: **GigaSpeech** (11,000 hours, approximately 9.9 million text and audio pairs).
3. Running on **4 x A100 GPUs (40GB)** on my GPU Node with a total of **500 GB VRAM**.

**Observed Behavior**:
Training begins but fails after 3k steps (out of 56471 steps to be completed) due to VRAM limitations, resulting in an OOM error. See the attached, that available memory dropped fro 398GB to 111GB (in the meantime of writing this is 70GB available). 

Attempts to lower the batch size and gradient accumulation steps partially alleviate the problem but limit effective batch size and training stability.

https://github.com/user-attachments/assets/68df2135-197c-4a92-be25-b26763395127

**Comment by SWivid** [comment]
Hi @atlonxp , feel free to check https://github.com/SWivid/F5-TTS/issues?q=is%3Aissue+oom if would help, e.g. #233

**Comment by atlonxp** [comment]
@SWivid yes i did check that. My case is not GPU VRAM -- but instead it is machine RAM. The more steps complete the more RAM consumed.

I was also looking at PR about checkpointing but it is still a bug.

**Comment by SWivid** [comment]
No idea then 😔

https://github.com/SWivid/F5-TTS/blob/3fcdbc70b4a9d4299e1ecd0b5a1c35209f23fd69/src/f5_tts/model/dataset.py#L248 would by default use `in_memory=False`

**Comment by atlonxp** [comment]
@SWivid Thanks for your prompt response. By the way, I'm working on Thai dataset above using gigaspeech. There are 9.9m data and I'm working on supercomputer (A100 40gb x 4) with Slurm. Do you have any recommendation for training hyperparameters?

it would help me a lot.

**Comment by atlonxp** [comment]
@SWivid I have added video recording -- just in case you would found the reason of memory leaks (or probably not)
@lpscr do you have any idea?

**Comment by atlonxp** [comment]
@SWivid Thank you for your response.

I have tested by turning persistent_workers=False as suggested. The issue still happens.

This guys also have the same issue: [57#discussioncomment-10981044](https://github.com/SWivid/F5-TTS/discussions/57#discussioncomment-10981044)

Here is my accelerate configurations

```
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
enable_cpu_affinity: false
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

Hyperparameters:
```
exp_name"F5TTS_Base"
learning_rate0.000075
batch_size_per_gpu16000
batch_size_type"frame"
max_samples64
grad_accumulation_steps78
max_grad_norm1
epochs100
num_warmup_updates20000
save_per_updates50000
last_per_steps5000
finetunetrue
file_checkpoint_train""
tokenizer_type"pinyin"
tokenizer_file""
mixed_precision"bf16"
logger"tensorboard"
```

**Comment by SWivid** [comment]
will `train.py` have same problem? we haven't try with finetune scripts on large dataset yet

**Comment by atlonxp** [comment]
@SWivid let me try training via `train.py` (instead of finetune_gradio.py). I will let you know

**Comment by atlonxp** [comment]
@SWivid still OOM. 

I think the problem might be this.
[DataLoader num_workers > 0 causes CPU memory from parent process to be replicated in all worker processes](https://github.com/pytorch/pytorch/issues/13246) 

I'm investigating on how CustomDataset is being called, also found out that it use many Python List, which I believe that might be the cause.

**Comment by SWivid** [comment]
Hi @atlonxp , agreed. I've heard about it long time ago from one of my colleagues, seems not totally fixed yet lol.
As we have got a `mmap` way (.arrow) of dataset organization, maybe 
1. explicitly set `torch.multiprocessing.set_start_method("spawn")` as default
2. using `num_workers=0`

are possible ways out as I grasped from discussions in the long-standing issue?
correct me if I got something wrong, with hope of facilitating the implementation of current and future works, many thanks!

**Comment by atlonxp** [comment]
@SWivid I have tested all cases and found that we need to experiment by testing num_workers=1 and see how much RAM it consumed. For my cases, my batch_size is 18000 (for A100 with 40GB; this is around half of your batch_size for A100 with 80G). So I did test num_workers = 1, 2, ..., and lastly 4 as my free memory is left available around 40GB. 

My assumption is that given the training configuration: batch_size = 18000, and grad_accumulation_steps = 1. One epoch takes around 100GB in RAM. I will test num_workers = 5 and onwards later.

Also, it might not be the case but I think it could probably cause the memory leak as well. It is `__getitem__` function in `CustomDataset` using recursive calls, which believably could lead to Memory Leak.

My assumption is that If there are consecutive samples with invalid durations, this recursive call can lead to a deep recursion stack, consuming a significant amount of memory and possibly causing a stack overflow.

```
def __getitem__(self, index):
    row = self.data[index]
    audio_path = row["audio_path"]
    text = row["text"]
    duration = row["duration"]

    if self.preprocessed_mel:
        mel_spec = torch.tensor(row["mel_spec"])
    else:
        audio, source_sample_rate = torchaudio.load(audio_path)
        if audio.shape[0] > 1:
            audio = torch.mean(audio, dim=0, keepdim=True)

        if duration > 30 or duration < 0.3:
            return self.__getitem__((index + 1) % len(self.data))    # << -- recursive park

        if source_sample_rate != self.target_sample_rate:
            resampler = torchaudio.transforms.Resample(source_sample_rate, self.target_sample_rate)
            audio = resampler(audio)

        mel_spec = self.mel_spectrogram(audio)
        mel_spec = mel_spec.squeeze(0)  # '1 d t -> d t')

        return dict(
            mel_spec=mel_spec,
            text=text,
        )
```

So, given this assumption, I have fixed by this way

```
def __getitem__(self, index):
    while True:
        row = self.data[index]
        audio_path = row["audio_path"]
        text = row["text"]
        duration = row["duration"]
    
        # Check if the duration is within the acceptable range
        if 0.3 <= duration <= 30:
            break  # Valid sample found, exit the loop
    
        # Move to the next index and wrap around if necessary
        index = (index + 1) % len(self.data)
    
    if self.preprocessed_mel:
        mel_spec = torch.tensor(row["mel_spec"])
    else:
        audio, source_sample_rate = torchaudio.load(audio_path)
    
        # If the audio has multiple channels, convert it to mono
        if audio.shape[0] > 1:
            audio = torch.mean(audio, dim=0, keepdim=True)
    
        # Resample the audio if necessary
        if source_sample_rate != self.target_sample_rate:
            resampler = torchaudio.transforms.Resample(source_sample_rate, self.target_sample_rate)
            audio = resampler(audio)
    
        # Compute the mel spectrogram
        mel_spec = self.mel_spectrogram(audio)
        mel_spec = mel_spec.squeeze(0)  # Convert from (1, D, T) to (D, T)
    
        return {
            "mel_spec": mel_spec,
            "text": text,
        }
```

If you think this make sense, I will create PR

**Comment by SWivid** [comment]
Hi @atlonxp , I'm quite sure the issue is not with `__getitem__` 
cuz it's a common way for a dataset class in that way, 
and if invalid samples with duration <0.3 encountered, will probably get a immediate cuda oom (since padding of many short samples to very possible long sample length) than a long term ram leak

we have experimented with batchsize 19200 on a machine with 250gb ram and with default setting of 16 workers, though cannot reproduce the error of mem leakage.

welcome to test if the modification takes effort in your case, it would be nice if will work

**Comment by atlonxp** [comment]
@SWivid Interesting -- now got me thinking what is the actual problem on my machine now. I will continue experiment further then. Let you know what I discover.

**Comment by nicholas-greig** [comment]
Stumbled across this from the link https://github.com/pytorch/pytorch/issues/13246, and just putting this here to try and help: if one of the machines you're trying to replicate on is using Windows or MacOS, the default torch multiprocessing method for those operating systems is 'spawn' and not 'fork', so if the mem leak is due to reference counting issues with 'fork' then it won't arise on that machine. You can also set 'shuffle=True' in the dataloader, and if the memory leak occurs more rapidly than with 'shuffle=False', then it points to the issue being the one discussed in the link above (which is solved by using objects that are reference counted once per total instance (ie numpy arrays, pandas dataframes etc.) and not using python native objects (where every entry is reference counted independently), or it is solved by using the multiprocessing method 'spawn' instead of fork).

**Comment by atlonxp** [comment]
@nicholas-greig This is very interesting suggestion. I will test it and let you know the results.

**Comment by saifulislam79** [comment]
@atlonxp and @SWivid, i have same issue of pre-train model training using large amount of dataset, Here i have share the training configuration,

- Total Duration:  34422.0 Hours
- H100 6 GPU = 80*6 = 480 GB VRAM
- 2 TB RAM
- vocab size = 8766
previous used = 38400 but current use 19200
`batch_size_per_gpu = 19200  # 8 GPUs, 8 * 38400 = 307200
batch_size_type = "frame"  # "frame" or "sample"
max_samples = 64  # max sequences per batch if use frame-wise batch_size. we set 32 for small models, 64 for base models
grad_accumulation_steps = 1  # note: updates = steps / grad_accumulation_steps
max_grad_norm = 1.0
`

And train also f5-tts small configuration,
`model_cfg = dict(
        dim=768, 
        depth=18, 
        heads=12, 
        ff_mult=2, 
        text_dim=512, 
        conv_layers=4
    )`

but after 1377 step training it raise cuda out of memory.  please let us know what the issue of pre-training when use large amount of data.

**Comment by atlonxp** [comment]
Per GPU, and you use **frames** instead of **samples** as` batch_size`

- if it is 40GB --> 19200 
- if it is 80GB --> 38400 should be fine.

My case is not about CUDA VRAM but instead the actual machine ram that caused by the Dataloader

**Comment by marklad** [comment]
@atlonxp Were you able to fix it? I see the same problem on my Mac.

**Comment by atlonxp** [comment]
> [@atlonxp](https://github.com/atlonxp) Were you able to fix it? I see the same problem on my Mac.

You need to reduce the number of process for data loader. 

The question is that which number would be appropriate? 
> You have to investigate manually while training, there are processes created by Dataloader. Look at how much memory it consumes (A), and what is your maximum ram available (B). Let's take 10% off as spare for operating system, so round_down(B*0.9 / A) that should be your number of processes for data loader.

Hope this would help.

**Comment by marklad** [comment]
@atlonxp Sorry I am not that deep into machine learning right now. It creates 16 processes each 525 MB each. I have 64GB RAM, which is shared with GPU on the Mac, of which you can utilise about 48 for GPU.

Currently I have num_workers = 14 (my cpu cores). With num_workers = 0 it crashes on start.

Do you mean something else with data loaders?
